<?php
  $caminho=$_POST["remetente"];
  $arr["introducao"]["cabec"]='Introducao';
  $arr["introducao"]["conte"]='<p>No momento atual, com a disseminação e popularização do acesso à internet, existe uma demanda justa: que estas informações estejam disponíveis para aqueles que tem limitações físicas ao acesso—dispor de alternativas para que um deficiente visual consiga acessar as informações, ou para que um deficiente físico consiga navegar pelas páginas com facilidade. Ou seja, aplicação de normas de acessibilidade para internet.</p><p>Para isto, existem normas e aplicações a serem aplicadas no desenvolvimento que auxiliam nesta acessibilidade, como na arquitetura, por exemplo, a construção de rampas de acesso para deficientes físicos ou pisos táteis para deficientes visuais.</p><p>E é um diferencial para quem busca uma especialização em desenvolvimento web, uma compreensão teórica e prática destes conceitos e o resultado destas boas práticas. E o objetivo deste webquest é que o aluno compreenda estes conceitos e tenha boas práticas para que viabilize esta acessibilidade.</p>';
  $arr["recursos"]["cabec"]="Recursos";
  $arr["recursos"]["conte"]='<p>Para recursos de pesquisa, temos as seguintes páginas para consulta:</p><ul> <li><a href="http://thiagopaiva.com/alunos/mod/forum/view.php?id=100">O Fórum que os alunos participaram,</a></li><li><a href="https://acessibilly.wordpress.com/">Acessibilly - O blog que os alunos participaram,</a></li><li><a href="https://pt.wikipedia.org/wiki/Dosvox">DOSVOX</a></li><li><a href="http://www.acessibilidadelegal.com/">Acessibilidade Legal</a></li><li><a href="https://www.w3.org/WAI/">WAI</a></li><li><a href="http://tableless.com.br/boas-praticas-de-acessibilidade/">Tableless - Boas Práticas</a></li><li><a href="http://tableless.com.br/como-tornar-seu-website-acessivel/">Tableless - Trabalhando com Acessibilidade</a></li><li><a href="http://tableless.com.br/acessibilidade-na-web-atualizando-como-tornar-seu-site-acessivel/">Tableless - Acessibilidade I</a></li><li><a href="http://tableless.com.br/semantica/acessibilidade-2/">Tableless - Acessibilidade II</a></li><li><a href="http://www.sidar.org/hera/">Hera (Validador)</a></li><li><a href="http://www.acessibilidade.gov.pt/webax/examinator.php">Examinator</a></li></ul>';
  $arr["processo"]["cabec"]="Processo";
  $arr["processo"]["conte"]='<p>Os alunos farão:</p><ol> <li>Pesquisa através de ajuda nos recursos;</li><li>Discutir sobre o assunto em um fórum com base no que foi pesquisado</li><li>Dissertar sobre o assunto e o que foi debatido no forum em um texto.</li><li>Desenvolver uma página que siga as boas práticas em acessibilidade.</li></ul>';
  $arr["tarefas"]["cabec"]="Tarefas";
  $arr["tarefas"]["conte"]='<p>Espera-se que o aluno:</p><ol> <li>Entenda a importância da acessibilidade para um mundo dito conectado;</li><li>Compreenda as diretrizes e boas práticas para o desenvolvimento de um site acessível.</li><li>Desenvolva uma página que contemple estas diretrizes.</li></ul>';
  $arr["avaliacao"]["cabec"]="Avaliação";
  $arr["avaliacao"]["conte"]="<p>A avaliação é realizada utilizando os seguintes critérios</p><h5>Processos itens 1 a 3</h5> <ul> <li>Demonstra plena compreensão do que representa a acessibilidade e sua importância para a sociedade hoje -10 Pontos</li><li>Demonstra parcial compreensão do que representa a acessibilidade e sua importância para a sociedade hoje -6 pontos</li></ul> <h5>Processo item 4</h5> <p>Os pontos serão calculados de acordo com os validadores hera e examinator .A pontuação será calculada como (NE)-(HR)</p><p> Sendo que <br/> NE – Nota do Examinator<br/> HR – Quantidade de erros classificados pelo Hera<br/> </p>A média das duas avaliações será a pontuação final.";
  $arr["conclusao"]["cabec"]="Conclusão";
  $arr["conclusao"]["conte"]="<p>A conclusão e o objetivo deste webquest é que o aluno compreenda e desenvolva a habilidade de criar páginas web com uma usabilidade intuitiva para todas as pessoas, e entenda que isto é além de tudo uma forma de inclusão social e digital.</p>";
  $ret=$arr[$caminho];
  //print_r($ret);
  echo json_encode($ret);
 ?>
